name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Only run one workflow at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt
        python3 -m pip install .
    - name: run unit tests
      run: |
        python3 -m unittest
